const TOGGLE_CART_HIDDEN: string = 'TOGGLE_CART_HIDDEN';
const ADD_ITEM: string = 'ADD_ITEM';
const CLEAR_ITEM_FROM_CART: string = 'CLEAR_ITEM_FROM_CART';
const REMOVE_ITEM: string = 'REMOVE_ITEM';

export { TOGGLE_CART_HIDDEN, ADD_ITEM, CLEAR_ITEM_FROM_CART, REMOVE_ITEM };
