const FECTH_COLLECTIONS_PENDING: string = 'FECTH_COLLECTIONS_PENDING';
const FECTH_COLLECTIONS_SUCCESS: string = 'FECTH_COLLECTIONS_SUCCESS';
const FECTH_COLLECTIONS_FAILURE: string = 'FECTH_COLLECTIONS_FAILURE';

export {
  FECTH_COLLECTIONS_PENDING,
  FECTH_COLLECTIONS_SUCCESS,
  FECTH_COLLECTIONS_FAILURE,
};
